# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  # コンテナ落として全て削除
  clean:
    cmds:
      - docker compose down --remove-orphans --rmi all --volumes
    silent: true
  
  # コンテナ落とす
  down:
    cmds:
      - docker compose down
    silent: true
  
  # コンテナ起動
  up:
    cmds:
      - docker compose up -d --build
    silent: true

  # データベース接続
  dbshell:
    cmds:
      - docker compose exec {{.DBContainer}} mysql -u root -p --password=$DBPassword
    env:
      DBPassword: root
    vars:
      DBContainer: mysql
    silent: true
  
  # データベースのリセット
  dbreset:
    cmds:
      - docker compose down mysql --volumes --remove-orphans
      - docker compose up mysql -d --build
    silent: true
  
  # 初回セットアップ
  setup:
    deps: [up]